I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/citas_point.rpy", line 46, in script
    show screen inventario2
  File "renpy/common/000statements.rpy", line 646, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen inventario2 is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/citas_point.rpy", line 46, in script
    show screen inventario2
  File "C:\Users\Pinwilly\OneDrive\Documentos\renpy-8.1.3-sdk\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "C:\Users\Pinwilly\OneDrive\Documentos\renpy-8.1.3-sdk\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\Pinwilly\OneDrive\Documentos\renpy-8.1.3-sdk\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 646, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "C:\Users\Pinwilly\OneDrive\Documentos\renpy-8.1.3-sdk\renpy\display\screen.py", line 1220, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen inventario2 is not known.


Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
prueba 1 1.0
Sat Nov  4 15:45:34 2023
